pipeline {
	agent any
    tools {
        maven 'maven-3.8.6'
    }
    environment {
    	DATE = new Date().format('yy.M')
        TAG = "${DATE}.${BUILD_NUMBER}"
		rancherCredential = 'Rancher'
        aliyuncsCredential = 'Aliyuncs'
		dockerRegistry = 'https://registry.cn-hangzhou.aliyuncs.com'
		dockerImage = 'registry.cn-hangzhou.aliyuncs.com/rlm/eureka-server'
		workloadUrl = '/project/c-m-6gmtml5x:p-nw76n/workloads/statefulset:renlm:eurekaserver'
    }
    stages {
        stage('Docker Build') {
            steps {
                script {
                	echo "构建镜像..."
                	dir("${WORKSPACE}") {
	                	docker.withRegistry("${dockerRegistry}", "${aliyuncsCredential}") {
	                        docker.build("${dockerImage}:${TAG}", "-f eureka-server/Dockerfile .")
	                    }
                    }
                }
            }
        }
	    stage('Publish Image') {
            steps {
                script {
                	echo "推送镜像..."
                    docker.withRegistry("${dockerRegistry}", "${aliyuncsCredential}") {
                        docker.image("${dockerImage}:${TAG}").push()
                        docker.image("${dockerImage}:${TAG}").push("latest")
                        sh "docker rmi ${dockerImage}:latest"
                        sh "docker rmi ${dockerImage}:${TAG}"
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                echo "部署应用..."
                rancherRedeploy alwaysPull: true, credential: "${rancherCredential}", images: "${dockerImage}", workload: "${workloadUrl}"
            }
        }
    }
}