spring:
  cloud:
    config:
      label: master
      failFast: true
      username: springCloud
      password: 123654
      discovery:
        enabled: true
        service-id: config-server
eureka:
  instance:
    preferIpAddress: false
    instanceId: ${EUREKA_INSTANCE_HOSTNAME:${spring.cloud.client.ip-address}}:${server.port}
    hostname: ${EUREKA_INSTANCE_HOSTNAME:${spring.cloud.client.ip-address}}
  client:
    registerWithEureka: ${REGISTER_WITH_EUREKA:true}
    fetchRegistry: ${FETCH_REGISTRY:true}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}