server:
   port: 9000
spring:
   application:
      name: config-server
   profiles:
      active: native
   cloud:
      config:
         server:
            native:
               searchLocations: classpath:/config
            git:
               uri: https://gitee.com/renlm/config-repo
               force-pull: true