spring:
   security:
      user:
         name: ${SECURITY_NAME:springCloud}
         password: ${SECURITY_PASSWORD:123654}
eureka:
   instance:
      preferIpAddress: false
      instanceId: ${EUREKA_INSTANCE_HOSTNAME:${spring.cloud.client.ip-address}}:${server.port}
      hostname: ${EUREKA_INSTANCE_HOSTNAME:${spring.cloud.client.ip-address}}
   client:
      registerWithEureka: ${REGISTER_WITH_EUREKA:true}
      fetchRegistry: ${FETCH_REGISTRY:false}
      serviceUrl:
         defaultZone: ${EUREKA_SERVER:http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/}