server:
  port: 80
management:
  server:
    port: 9000
spring:
  profiles:
    active: prod
eureka:
  datacenter: cloud
  environment: product
  instance:
    preferIpAddress: false
    hostname: ${HOSTNAME}
    nonSecurePort: ${server.port}
    instanceId: ${eureka.instance.hostname}:${eureka.instance.nonSecurePort}
  client:
    registerWithEureka: ${REGISTER_WITH_EUREKA:true}
    fetchRegistry: ${FETCH_REGISTRY:true}
    webclient:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}