server:
  port: 80
spring:
  application:
    name: eureka-server
  profiles:
    active: prod
management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  level:
    root: INFO
  file:
    name: /opt/log/eurekaServer.log
  logback:
    rollingpolicy:
      maxFileSize: 512MB
      maxHistory: 30
eureka:
  datacenter: cloud
  environment: product
  instance:
    preferIpAddress: false
    hostname: ${HOSTNAME}
    nonSecurePort: ${server.port}
    instanceId: ${eureka.instance.hostname}:${eureka.instance.nonSecurePort}
  client:
    registerWithEureka: ${REGISTER_WITH_EUREKA:true}
    fetchRegistry: ${FETCH_REGISTRY:true}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}