eureka:
  datacenter: cloud
  environment: product
  instance:
    preferIpAddress: false
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    nonSecurePort: ${server.port}
    instanceId: ${eureka.instance.hostname}:${eureka.instance.nonSecurePort}
  client:
    registerWithEureka: ${REGISTER_WITH_EUREKA:true}
    fetchRegistry: ${FETCH_REGISTRY:false}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}