spring:
   security:
      user:
         name: springCloud
         password: 123654
   rabbitmq:
      virtual-host: /renlm
      host: rabbitmq.renlm.cn
      port: 30672
      username: renlm
      password: MR1bi1Q^YhtMKit_0lcsmRa78Q^02dfs
   cloud:
      config:
         server:
            git:
               uri: https://gitee.com/renlm/config-repo
               forcePull: true
               defaultLabel: master
eureka:
   instance:
      preferIpAddress: false
      instanceId: ${EUREKA_INSTANCE_HOSTNAME:${spring.cloud.client.ip-address}}:${server.port}
      hostname: ${EUREKA_INSTANCE_HOSTNAME:${spring.cloud.client.ip-address}}
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: ${EUREKA_SERVER:http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/}