server:
   port: 7000
management:
   endpoints:
      web:
         exposure:
            include: "*"
eureka:
   instance:
      preferIpAddress: true
      instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
   client:
      serviceUrl:
         defaultZone: http://localhost:7001/eureka
spring:
   cloud:
      config:
         server:
            git:
               uri: https://gitee.com/renlm/config-repo
               forcePull: true
               defaultLabel: master
   rabbitmq:
      virtual-host: /renlm
      host: rabbitmq.renlm.cn
      port: 30672
      username: renlm
      password: MR1bi1Q^YhtMKit_0lcsmRa78Q^02dfs