spring:
   cloud:
      config:
         server:
            git:
               uri: https://gitee.com/renlm/config-repo
               forcePull: true
               searchPaths: '{profile}'
eureka:
   instance:
      preferIpAddress: false
      instanceId: ${EUREKA_INSTANCE_HOSTNAME:localhost}:${server.port}
      hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://springCloud:123654@localhost:7001/eureka/